# Generated by Django 2.2.4 on 2019-12-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvet', models.IntegerField()),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('idanimal', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('termino', models.TimeField(blank=True, null=True)),
                ('comparecimento', models.IntegerField()),
                ('obs', models.CharField(blank=True, max_length=1000, null=True)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('idanimal', models.AutoField(primary_key=True, serialize=False)),
                ('idclie', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('especie', models.CharField(blank=True, max_length=30, null=True)),
                ('raca', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo', models.CharField(blank=True, max_length=18, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('castrado', models.CharField(blank=True, max_length=20, null=True)),
                ('cor', models.CharField(blank=True, max_length=40, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('obs', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
                ('sexo', models.CharField(blank=True, max_length=9, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.CharField(blank=True, max_length=6, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('complemento', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idficha', models.AutoField(primary_key=True, serialize=False)),
                ('idanimal', models.IntegerField()),
                ('idvacina', models.IntegerField()),
                ('idfunc', models.IntegerField()),
                ('data', models.DateField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('diagnostico', models.CharField(blank=True, max_length=5000, null=True)),
                ('historico', models.CharField(blank=True, max_length=9000, null=True)),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('contato', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'fornecedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('funcao', models.CharField(blank=True, max_length=30, null=True)),
                ('crmv', models.CharField(blank=True, max_length=30, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('rua', models.CharField(blank=True, max_length=60, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pessoas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=300, null=True)),
                ('pat', models.CharField(blank=True, max_length=50, null=True)),
                ('vet', models.CharField(blank=True, max_length=50, null=True)),
                ('retorno', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'receita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('idvacina', models.AutoField(primary_key=True, serialize=False)),
                ('idanimal', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('vacina', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'vacina',
                'managed': False,
            },
        ),
    ]
